// packages/react/src/GridView.tsx
import * as React from "react"
import type {
  Cell,
  ColumnHeaderState,
  GridRuntime
} from "@busted-grid/runtime"
import { useGrid } from "./useGrid.js"

export interface GridViewProps {
  runtime: GridRuntime
  rows: number
  cols: number
  idPrefix?: string
  scrollRef?: React.RefObject<HTMLDivElement>
  renderCell?: (cell: Cell) => React.ReactNode
  renderHeaderCell?: (header: ColumnHeaderState) => React.ReactNode
  stickyHeader?: boolean
  virtualization?: {
    rowHeight: number
    width: number
    height: number
    overscan?: number
  }
}

const defaultRenderer = (cell: Cell) => `${cell.row},${cell.col}`

export function GridView({
  runtime,
  rows,
  cols,
  idPrefix: idPrefixProp,
  scrollRef: scrollRefProp,
  renderCell = defaultRenderer,
  renderHeaderCell,
  stickyHeader = false,
  virtualization
}: GridViewProps): JSX.Element {
  const idPrefix = idPrefixProp ?? React.useId()
  const internalScrollRef = React.useRef<HTMLDivElement>(null)
  const lastFocusRef = React.useRef<{ row: number; col: number } | null>(null)
  const scrollRef = scrollRefProp ?? internalScrollRef
  const [scroll, setScroll] = React.useState({ top: 0, left: 0 })
  const viewport = virtualization
    ? {
      rows,
      cols,
      rowHeight: virtualization.rowHeight,
      viewportHeight: virtualization.height,
      scrollTop: scroll.top,
      overscan: virtualization.overscan
    }
    : undefined
  const vm = useGrid(runtime, viewport)
  const overscan = virtualization?.overscan ?? 2
  const rowHeight = virtualization?.rowHeight ?? 1
  const useVirtual = !!virtualization
  const rowStart = useVirtual
    ? Math.max(0, Math.floor(scroll.top / rowHeight) - overscan)
    : 0
  const rowEnd = useVirtual
    ? Math.min(
      rows - 1,
      rowStart +
      Math.ceil(virtualization.height / rowHeight) +
      overscan * 2 -
      1
    )
    : rows - 1
  const topOffset = useVirtual ? rowStart * rowHeight : 0
  const bottomOffset = useVirtual
    ? Math.max(0, rows - rowEnd - 1) * rowHeight
    : 0
  const rowIndexes = Array.from(
    { length: Math.max(0, rowEnd - rowStart + 1) },
    (_, i) => rowStart + i
  )
  const colIndexes = Array.from({ length: cols }, (_, i) => i)
  const activeDescendant = vm.focus
    ? `${idPrefix}-cell-${vm.focus.row}-${vm.focus.col}`
    : undefined

  const colWidths = React.useMemo(() => {
    return Array.from({ length: cols }, (_, index) => {
      const column = vm.columns[index]
      return column?.width ?? 120
    })
  }, [cols, vm.columns])

  const colLeftOffsets = React.useMemo(() => {
    const offsets = new Array<number>(cols)
    let current = 0
    for (let i = 0; i < cols; i++) {
      offsets[i] = current
      current += colWidths[i] ?? 0
    }
    return offsets
  }, [cols, colWidths])

  const headerByCol = React.useMemo(() => {
    const map = new Map<number, ColumnHeaderState>()
    for (const header of vm.headers) {
      map.set(header.col, header)
    }
    return map
  }, [vm.headers])

  const table = (
    <table
      tabIndex={0}
      role="grid"
      aria-rowcount={rows + 1}
      aria-colcount={cols}
      aria-multiselectable={vm.selectionRange ? "true" : "false"}
      aria-activedescendant={activeDescendant}
      className={stickyHeader ? "busted-grid-sticky-header" : undefined}
    >
      <colgroup>
        {colWidths.map((width, index) => (
          <col key={index} style={{ width }} />
        ))}
      </colgroup>
      <thead>
        <tr role="row" aria-rowindex={1}>
          {colIndexes.map(c => {
            const header =
              headerByCol.get(c) ??
              ({
                col: c,
                label: `Column ${c + 1}`,
                width: colWidths[c] ?? 120,
                sort: null,
                filterActive: false,
                canSort: true,
                canFilter: true,
                canResize: true
              } satisfies ColumnHeaderState)

            const sortLabel =
              header.sort === "asc"
                ? "asc"
                : header.sort === "desc"
                  ? "desc"
                  : ""

            return (
              <th
                key={c}
                role="columnheader"
                scope="col"
                aria-colindex={c + 1}
                aria-sort={
                  header.sort === "asc"
                    ? "ascending"
                    : header.sort === "desc"
                      ? "descending"
                      : "none"
                }
                data-filter={header.filterActive || undefined}
                data-sort={header.sort ?? "none"}
                className="grid-header-cell"
              >
                <div className="grid-header-inner">
                  <button
                    type="button"
                    tabIndex={-1}
                    className="grid-header-label"
                    data-busted-grid-header-control="sort"
                    data-busted-grid-col={c}
                    disabled={!header.canSort}
                    onClick={() =>
                      runtime.dispatch({
                        type: "TOGGLE_COLUMN_SORT",
                        col: c
                      })
                    }
                  >
                    {renderHeaderCell
                      ? renderHeaderCell(header)
                      : header.label}
                    {sortLabel ? ` (${sortLabel})` : ""}
                  </button>
                  <button
                    type="button"
                    tabIndex={-1}
                    className="grid-header-filter"
                    data-busted-grid-header-control="filter"
                    data-busted-grid-col={c}
                    disabled={!header.canFilter}
                    aria-pressed={header.filterActive}
                    onClick={() =>
                      runtime.dispatch({
                        type: "SET_COLUMN_FILTER",
                        col: c,
                        active: !header.filterActive
                      })
                    }
                  >
                    Filter
                  </button>
                  <div
                    className="grid-header-resize"
                    role="presentation"
                    onPointerDown={event => {
                      if (!header.canResize) return
                      event.preventDefault()
                      const startX = event.clientX
                      const startWidth = header.width
                      const handleMove = (moveEvent: PointerEvent) => {
                        const nextWidth = Math.max(
                          20,
                          Math.round(
                            startWidth + (moveEvent.clientX - startX)
                          )
                        )
                        runtime.dispatch({
                          type: "SET_COLUMN_WIDTH",
                          col: c,
                          width: nextWidth
                        })
                      }
                      const handleUp = () => {
                        window.removeEventListener("pointermove", handleMove)
                        window.removeEventListener("pointerup", handleUp)
                      }
                      window.addEventListener("pointermove", handleMove)
                      window.addEventListener("pointerup", handleUp)
                    }}
                    data-disabled={!header.canResize || undefined}
                  />
                </div>
              </th>
            )
          })}
        </tr>
      </thead>
      <tbody>
        {useVirtual && topOffset > 0 && (
          <tr role="presentation" aria-hidden="true" data-testid="top-offset-row">
            <td
              role="presentation"
              aria-hidden="true"
              colSpan={cols}
              style={{ height: topOffset, border: "none", padding: 0 }}
            />
          </tr>
        )}

        {rowIndexes.map(r => (
          <tr
            key={r}
            role="row"
            aria-rowindex={r + 2}
            style={
              useVirtual ? { height: virtualization?.rowHeight } : undefined
            }
          >
            {colIndexes.map(c => {
              const cell = { row: r, col: c }
              const focused = vm.focus?.row === r && vm.focus?.col === c
              const range = vm.selectionRange
              const selected =
                !!range &&
                r >= range.start.row &&
                r <= range.end.row &&
                c >= range.start.col &&
                c <= range.end.col
              const edit = vm.edit
              const editing =
                edit.status === "editing" &&
                !!edit.cell &&
                edit.cell.row === r &&
                edit.cell.col === c

              return (
                <td
                  key={c}
                  data-focused={focused || undefined}
                  data-selected={selected || undefined}
                  data-editing={editing || undefined}
                  role="gridcell"
                  aria-colindex={c + 1}
                  aria-selected={selected}
                  id={`${idPrefix}-cell-${r}-${c}`}
                  onClick={event => {
                    if (event.shiftKey) {
                      const anchor = vm.selection.anchor ?? vm.focus
                      if (!anchor) {
                        runtime.dispatch({ type: "SET_ANCHOR", cell })
                      }
                      runtime.dispatch({ type: "EXTEND_SELECTION", cell })
                      return
                    }
                    runtime.dispatch({ type: "SELECT_CELL", cell })
                  }}
                >
                  {renderCell(cell)}
                </td>
              )
            })}
          </tr>
        ))}
        {useVirtual && bottomOffset > 0 && (
          <tr role="presentation" aria-hidden="true">
            <td
              role="presentation"
              aria-hidden="true"
              colSpan={cols}
              style={{ height: bottomOffset, border: "none", padding: 0 }}
            />
          </tr>
        )}
      </tbody>
    </table>
  )

  React.useLayoutEffect(() => {
    if (!virtualization) return
    const focus = vm.focus
    const container = scrollRef.current
    if (!focus || !container) {
      lastFocusRef.current = null
      return
    }

    // Only auto-scroll if the focus has actually changed
    const focusChanged =
      !lastFocusRef.current ||
      lastFocusRef.current.row !== focus.row ||
      lastFocusRef.current.col !== focus.col

    if (!focusChanged) return
    lastFocusRef.current = focus

    const viewHeight = virtualization.height
    const viewWidth = virtualization.width
    const cellTop = focus.row * virtualization.rowHeight
    const cellBottom = cellTop + virtualization.rowHeight
    const cellLeft = colLeftOffsets[focus.col] ?? 0
    const cellRight = cellLeft + (colWidths[focus.col] ?? 0)
    let nextTop = container.scrollTop
    let nextLeft = container.scrollLeft

    if (cellTop < nextTop) {
      nextTop = cellTop
    } else if (cellBottom > nextTop + viewHeight) {
      nextTop = cellBottom - viewHeight
    }

    if (cellLeft < nextLeft) {
      nextLeft = cellLeft
    } else if (cellRight > nextLeft + viewWidth) {
      nextLeft = cellRight - viewWidth
    }

    if (nextTop !== scroll.top || nextLeft !== scroll.left) {
      // Synchronize both React state and DOM scroll position
      container.scrollTop = nextTop
      container.scrollLeft = nextLeft
      setScroll({ top: nextTop, left: nextLeft })
    }
  }, [
    colLeftOffsets,
    colWidths,
    virtualization,
    vm.focus
  ])

  if (!virtualization) {
    return table
  }

  return (
    <div
      ref={scrollRef}
      style={{
        width: virtualization.width,
        height: virtualization.height,
        overflow: "auto"
      }}
      onScroll={event => {
        const target = event.currentTarget
        setScroll({
          top: target.scrollTop,
          left: target.scrollLeft
        })
      }}
    >
      {table}
    </div>
  )
}

// packages/angular/src/grid-view.component.ts
import { CommonModule } from "@angular/common"
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  TemplateRef,
  ViewChild
} from "@angular/core"
import type {
  Cell,
  GridRuntime,
  GridViewModel
} from "@busted-grid/runtime"

export interface GridCellTemplateContext {
  $implicit: Cell
  cell: Cell
}

@Component({
  selector: "busted-grid-view",
  standalone: true,
  imports: [CommonModule],
  styles: [
    `
      .grid-scroller {
        display: block;
      }

      table {
        border-collapse: collapse;
      }

      table.sticky-header thead th {
        position: sticky;
        top: 0;
        z-index: 2;
        background: #fff;
      }

      th,
      td {
        border: 1px solid #ccc;
        padding: 4px 8px;
      }

      td[data-focused] {
        outline: 2px solid #3b82f6;
        outline-offset: -2px;
      }

      td[data-selected] {
        background: #dbeafe;
      }

      td[data-editing] {
        outline: 2px solid #f59e0b;
        outline-offset: -2px;
      }

      td.spacer {
        border: none;
        padding: 0;
      }

      th.grid-header-cell {
        padding: 0;
        text-align: left;
      }

      .grid-header-inner {
        display: flex;
        align-items: center;
        gap: 8px;
        padding: 4px 8px;
        position: relative;
      }

      .grid-header-label,
      .grid-header-filter {
        border: 1px solid transparent;
        background: none;
        padding: 2px 4px;
        cursor: pointer;
        font: inherit;
      }

      .grid-header-label:disabled,
      .grid-header-filter:disabled {
        cursor: not-allowed;
        opacity: 0.5;
      }

      .grid-header-resize {
        position: absolute;
        right: 0;
        top: 0;
        width: 6px;
        height: 100%;
        cursor: col-resize;
      }

      .grid-header-resize[data-disabled="true"] {
        cursor: not-allowed;
        opacity: 0.4;
      }
    `
  ],
  template: `
    <div
      class="grid-scroller"
      #scroller
      [style.height.px]="virtualization?.height"
      [style.width.px]="virtualization?.width"
      [style.overflow]="virtualization ? 'auto' : null"
      (scroll)="onScroll($event)"
    >
      <table
        tabindex="0"
        role="grid"
        [attr.aria-rowcount]="rows + 1"
        [attr.aria-colcount]="cols"
        [attr.aria-multiselectable]="vm.selectionRange ? 'true' : 'false'"
        [attr.aria-activedescendant]="activeDescendantId()"
        [class.sticky-header]="stickyHeader"
      >
        <colgroup>
          <col
            *ngFor="let colWidth of colWidths; trackBy: trackCol"
            [style.width.px]="colWidth"
          />
        </colgroup>
        <thead>
          <tr role="row" aria-rowindex="1">
            <th
              *ngFor="let header of headers; trackBy: trackCol"
              role="columnheader"
              scope="col"
              class="grid-header-cell"
              [attr.aria-colindex]="header.col + 1"
              [attr.aria-sort]="ariaSort(header.sort)"
              [attr.data-filter]="header.filterActive ? '' : null"
              [attr.data-sort]="header.sort ?? 'none'"
            >
              <div class="grid-header-inner">
                <button
                  type="button"
                  tabindex="-1"
                  class="grid-header-label"
                  data-busted-grid-header-control="sort"
                  [attr.data-busted-grid-col]="header.col"
                  (click)="toggleSort(header.col)"
                  [disabled]="!header.canSort"
                >
                  {{ header.label }}
                  <span *ngIf="header.sort">({{ header.sort }})</span>
                </button>
                <button
                  type="button"
                  tabindex="-1"
                  class="grid-header-filter"
                  data-busted-grid-header-control="filter"
                  [attr.data-busted-grid-col]="header.col"
                  (click)="toggleFilter(header.col)"
                  [attr.aria-pressed]="header.filterActive"
                  [disabled]="!header.canFilter"
                >
                  Filter
                </button>
                <div
                  class="grid-header-resize"
                  role="presentation"
                  (pointerdown)="startResize(header, $event)"
                  [attr.data-disabled]="!header.canResize ? 'true' : null"
                ></div>
              </div>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr *ngIf="virtualization && topOffset > 0" role="presentation">
            <td
              class="spacer"
              role="presentation"
              aria-hidden="true"
              [attr.colspan]="cols"
              [style.height.px]="topOffset"
            ></td>
          </tr>
          <tr
            *ngFor="let r of rowIndexes; trackBy: trackRow"
            role="row"
            [attr.aria-rowindex]="r + 2"
            [style.height.px]="virtualization?.rowHeight"
          >
            <td
              *ngFor="let c of colIndexes; trackBy: trackCol"
              [attr.data-focused]="isFocused(r, c) ? '' : null"
              [attr.data-selected]="isSelected(r, c) ? '' : null"
              [attr.data-editing]="isEditing(r, c) ? '' : null"
              role="gridcell"
              [attr.aria-colindex]="c + 1"
              [attr.aria-selected]="isSelected(r, c) ? 'true' : 'false'"
              [attr.id]="cellId(r, c)"
              [style.height.px]="virtualization?.rowHeight"
              (click)="onCellClick(r, c, $event)"
            >
              <ng-container *ngIf="cellTemplate; else defaultCell"
                [ngTemplateOutlet]="cellTemplate"
                [ngTemplateOutletContext]="cellContext(r, c)"
              ></ng-container>
              <ng-template #defaultCell>
                {{ r }},{{ c }}
              </ng-template>
            </td>
          </tr>
          <tr *ngIf="virtualization && bottomOffset > 0" role="presentation">
            <td
              class="spacer"
              role="presentation"
              aria-hidden="true"
              [attr.colspan]="cols"
              [style.height.px]="bottomOffset"
            ></td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class GridViewComponent
  implements OnInit, OnDestroy, OnChanges
{
  @Input({ required: true }) runtime!: GridRuntime
  @Input({ required: true }) rows!: number
  @Input({ required: true }) cols!: number
  @Input() cellTemplate?: TemplateRef<GridCellTemplateContext>
  @Input() stickyHeader = false
  @Input() virtualization?: {
    rowHeight: number
    width: number
    height: number
    overscan?: number
  }

  vm: GridViewModel = {
    focus: null,
    selection: { anchor: null, rangeEnd: null },
    selectionRange: null,
    edit: { status: "idle", cell: null },
    columns: [],
    headers: []
  }
  rowIndexes: number[] = []
  colIndexes: number[] = []
  headers: GridViewModel["headers"] = []
  colWidths: number[] = []
  readonly idPrefix = `busted-grid-${Math.random()
    .toString(36)
    .slice(2)}`
  @ViewChild("scroller") scroller?: ElementRef<HTMLDivElement>
  rowStart = 0
  rowEnd = -1
  topOffset = 0
  bottomOffset = 0
  private scrollTop = 0
  private scrollLeft = 0
  private lastFocusKey: string | null = null

  readonly trackRow = (_idx: number, row: number) => row
  readonly trackCol = (_idx: number, col: number) => col

  private unsubscribeRuntime?: () => void

  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.rowIndexes = createIndexArray(this.rows)
    this.colIndexes = createIndexArray(this.cols)
    this.attachRuntime()
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["rows"] && !changes["rows"].isFirstChange()) {
      this.rowIndexes = createIndexArray(this.rows)
    }
    if (changes["cols"] && !changes["cols"].isFirstChange()) {
      this.colIndexes = createIndexArray(this.cols)
    }
    if (changes["virtualization"] && !changes["virtualization"].isFirstChange()) {
      this.updateViewModel()
    }
    if (changes["runtime"] && !changes["runtime"].isFirstChange()) {
      this.attachRuntime()
    }
  }

  ngOnDestroy(): void {
    this.unsubscribe()
  }

  onCellClick(row: number, col: number, event: MouseEvent): void {
    if (!this.runtime) return
    const cell = { row, col }
    if (event.shiftKey) {
      const anchor = this.vm.selection.anchor ?? this.vm.focus
      if (!anchor) {
        this.runtime.dispatch({ type: "SET_ANCHOR", cell })
      }
      this.runtime.dispatch({ type: "EXTEND_SELECTION", cell })
      return
    }
    this.runtime.dispatch({ type: "SELECT_CELL", cell })
  }

  isFocused(row: number, col: number): boolean {
    const focus = this.vm.focus
    return !!focus && focus.row === row && focus.col === col
  }

  isSelected(row: number, col: number): boolean {
    const range = this.vm.selectionRange
    if (!range) return false
    return (
      row >= range.start.row &&
      row <= range.end.row &&
      col >= range.start.col &&
      col <= range.end.col
    )
  }

  isEditing(row: number, col: number): boolean {
    const edit = this.vm.edit
    return (
      edit.status === "editing" &&
      !!edit.cell &&
      edit.cell.row === row &&
      edit.cell.col === col
    )
  }

  cellId(row: number, col: number): string {
    return `${this.idPrefix}-cell-${row}-${col}`
  }

  activeDescendantId(): string | null {
    const focus = this.vm.focus
    if (!focus) return null
    return this.cellId(focus.row, focus.col)
  }

  onScroll(event: Event): void {
    if (!this.virtualization) return
    const target = event.target as HTMLElement
    this.scrollTop = target.scrollTop
    this.scrollLeft = target.scrollLeft
    this.updateViewModel()
  }

  toggleSort(col: number): void {
    this.runtime.dispatch({ type: "TOGGLE_COLUMN_SORT", col })
  }

  toggleFilter(col: number): void {
    const header = this.headers.find(item => item.col === col)
    this.runtime.dispatch({
      type: "SET_COLUMN_FILTER",
      col,
      active: !(header?.filterActive ?? false)
    })
  }

  ariaSort(sort: GridViewModel["headers"][number]["sort"]): string {
    if (sort === "asc") return "ascending"
    if (sort === "desc") return "descending"
    return "none"
  }

  startResize(
    header: GridViewModel["headers"][number],
    event: PointerEvent
  ): void {
    if (!header.canResize) return
    event.preventDefault()
    const startX = event.clientX
    const startWidth = header.width
    const move = (moveEvent: PointerEvent) => {
      const nextWidth = Math.max(
        20,
        Math.round(startWidth + (moveEvent.clientX - startX))
      )
      this.runtime.dispatch({
        type: "SET_COLUMN_WIDTH",
        col: header.col,
        width: nextWidth
      })
    }
    const up = () => {
      window.removeEventListener("pointermove", move)
      window.removeEventListener("pointerup", up)
    }
    window.addEventListener("pointermove", move)
    window.addEventListener("pointerup", up)
  }

  cellContext(row: number, col: number): GridCellTemplateContext {
    const cell = { row, col }
    return { $implicit: cell, cell }
  }

  private attachRuntime(): void {
    this.unsubscribe()
    if (!this.runtime) return

    this.vm = this.runtime.getViewModel(this.getViewportConfig())
    this.updateVirtualization()
    this.unsubscribeRuntime = this.runtime.subscribe(() => {
      this.updateViewModel()
    })
    this.cdr.markForCheck()
  }

  private unsubscribe(): void {
    this.unsubscribeRuntime?.()
    this.unsubscribeRuntime = undefined
  }

  private updateViewModel(): void {
    if (!this.runtime) return
    this.vm = this.runtime.getViewModel(this.getViewportConfig())
    this.updateVirtualization()
    this.ensureFocusVisible()
    this.cdr.markForCheck()
  }

  private getViewportConfig() {
    if (!this.virtualization) return undefined
    return {
      rows: this.rows,
      cols: this.cols,
      rowHeight: this.virtualization.rowHeight,
      viewportHeight: this.virtualization.height,
      scrollTop: this.scrollTop,
      overscan: this.virtualization.overscan
    }
  }

  private updateVirtualization(): void {
    this.headers = this.vm.headers
    this.colWidths = createIndexArray(this.cols).map(
      idx => this.vm.columns[idx]?.width ?? 120
    )

    if (!this.virtualization || !this.vm.viewport) {
      this.rowIndexes = createIndexArray(this.rows)
      this.colIndexes = createIndexArray(this.cols)
      this.rowStart = 0
      this.rowEnd = this.rows - 1
      this.topOffset = 0
      this.bottomOffset = 0
      return
    }

    const rowRange = this.vm.viewport.rowRange
    this.rowStart = Math.max(0, rowRange.start)
    this.rowEnd = Math.min(this.rows - 1, rowRange.end)

    if (this.rowEnd < this.rowStart) {
      this.rowIndexes = []
      this.topOffset = 0
      this.bottomOffset = 0
      return
    }

    this.rowIndexes = createIndexArray(this.rowEnd - this.rowStart + 1).map(
      idx => this.rowStart + idx
    )
    this.colIndexes = createIndexArray(this.cols)
    this.topOffset = this.rowStart * this.virtualization.rowHeight
    this.bottomOffset =
      Math.max(0, this.rows - this.rowEnd - 1) *
      this.virtualization.rowHeight
  }

  private ensureFocusVisible(): void {
    if (!this.virtualization) return
    const focus = this.vm.focus
    if (!focus) {
      this.lastFocusKey = null
      return
    }
    const focusKey = `${focus.row}:${focus.col}`
    if (focusKey === this.lastFocusKey) return
    this.lastFocusKey = focusKey
    const scroller = this.scroller?.nativeElement
    if (!scroller) return
    const viewHeight = this.virtualization.height
    const viewWidth = this.virtualization.width
    const cellTop = focus.row * this.virtualization.rowHeight
    const cellBottom = cellTop + this.virtualization.rowHeight
    const cellLeft = this.colWidths
      .slice(0, focus.col)
      .reduce((sum, width) => sum + width, 0)
    const cellRight = cellLeft + (this.colWidths[focus.col] ?? 120)
    let nextTop = scroller.scrollTop
    let nextLeft = scroller.scrollLeft

    if (cellTop < nextTop) {
      nextTop = cellTop
    } else if (cellBottom > nextTop + viewHeight) {
      nextTop = cellBottom - viewHeight
    }

    if (cellLeft < nextLeft) {
      nextLeft = cellLeft
    } else if (cellRight > nextLeft + viewWidth) {
      nextLeft = cellRight - viewWidth
    }

    if (nextTop !== scroller.scrollTop) {
      scroller.scrollTop = nextTop
      this.scrollTop = nextTop
    }
    if (nextLeft !== scroller.scrollLeft) {
      scroller.scrollLeft = nextLeft
      this.scrollLeft = nextLeft
    }
  }
}

function createIndexArray(count: number): number[] {
  const safeCount = Math.max(0, count | 0)
  return Array.from({ length: safeCount }, (_, idx) => idx)
}
